services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - FRONTEND_URL=http://frontend:3000
      - BACKEND_URL=http://backend:3001
      - AUTH_URL=http://localhost:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - ./.env
    environment:
      - FRONTEND_URL=http://localhost:3000

networks:
  app-network:
    driver: bridge
